### PR TITLE
Create Medical School Use

### PR DESCRIPTION
**Pull request by tamugreenqueen3210**
Hello! I am working on a gender bias project with medical school narratives. We love you calculator but there are some medical school specific terminology and modifications. We need to process data in the next week so please let me know if this modification is possible for a use on my end. Thank you!

### CODE REVIEW

**Comment by slowe** [comment]
I apologise for not getting back to you faster but my dad had been declining over the past few days and he died yesterday.

There are a few issues with quotation marks and escaping of special characters. Also I'd like to avoid having a separate version of the Javascript - I'd rather that use-case-specific dictionaries are created. I'll add my suggested changes to this pull request shortly. @tamugreenqueen3210 Do you have a preferred/suggested way that your dictionary could be referred to? At the moment I'm thinking "Medical school specific" but it may be helpful to have some thing a little more specific/descriptive even if just which country's medical school this may be appropriate for.

**Comment by slowe** [comment]
@tamugreenqueen3210 Hopefully my changes to your pull request meet with what you were trying to achieve. I've basically added a drop down box to select the source dictionary. 
Screenshot 2023-02-16 at 11-40-27 Gender-bias calculator
There are two options in the drop-down: the original word lists and your medical-school-specific ones. You may wish to change/update the `_about` details in the new [`dictionaries/medical.json`](https://github.com/slowe/genderbias/pull/5/files#diff-778d7ca8e1d8a8038666bd5a7741ea50778562ca627744dab644f9e074b9b053) file in this pull request to better credit you?

**Comment by slowe** [comment]
@tamugreenqueen3210 Let me know if my additions/changes are OK and I'll merge this.

**Comment by tamugreenqueen3210** [comment]
Hello Stuart,

Thank you so much for your response and I am so sorry for your father's
passing.

These changes look great. Thank you so much!

Uma Reddy

**Comment by tamugreenqueen3210** [comment]
Hello Stuart,

I was wondering if it would be possible to temporarily take the Medical
School Specific words tab off of the Gender Bias Calculator. We are working
on creating a fully relevant and evidence-based list of Medical School
specific words and hope to get it done by the end of July. Is that okay
with you and would that be possible? I can send you this final list on July
31st if it is.

Thank you so much,
Uma Reddy

**Pull request merged**
